admin: 
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
        
dpavic_jobs:
    resource: "@DpavicJobsBundle/Resources/config/routing.yml"
    prefix:   /

