dpavic_jobs_homepage:
    path:     /
    defaults: { _controller: DpavicJobsBundle:Job:index}
    
jobs: 
    resource: "@DpavicJobsBundle/Controller/JobController.php"
    type:   annotation

category:
    resource: "@DpavicJobsBundle/Controller/CategoryController.php"
    type:   annotation