services:
#    dpavic_jobs.example:
#        class: Dpavic\JobsBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    dpavic.jobs.admin.category:
        class: Dpavic\JobsBundle\Admin\CategoryAdmin
        tags: 
            - { name: sonata.admin, manager_type: orm , group: jobs, label: Categories }
        arguments:
            - ~
            - Dpavic\JobsBundle\Entity\Category
            - 'DpavicJobsBundle:CategoryAdmin'
            
    dpavic.jobs.admin.job:
        class: Dpavic\JobsBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobs, label: Jobs }
        arguments:
            - ~
            - Dpavic\JobsBundle\Entity\Job
            - 'DpavicJobsBundle:JobAdmin'
            
    dpavic.jobs.admin.affiliate:
        class: Dpavic\JobsBundle\Admin\AffiliateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobs, label: Affiliates }
        arguments:
            - ~
            - Dpavic\JobsBundle\Entity\Affiliate
            - 'DpavicJobsBundle:AffiliateAdmin'
